# Generated by Django 5.2.17 on 2026-09-16 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=5)),
                ('value', models.CharField(max_length=320)),
                ('label', models.TextField(default=None, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_points', to='crm.party')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='contact_positive_version'), models.CheckConstraint(condition=models.Q(('kind__in', ['email', 'phone'])), name='contact_valid_kind'), models.UniqueConstraint(fields=('workspace', 'id'), name='contact_workspace_id')],
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_contactpoint ADD CONSTRAINT contact_party_workspace_fk "
            "FOREIGN KEY (workspace_id, party_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_contactpoint DROP CONSTRAINT contact_party_workspace_fk",
        ),
    ]
