# Generated by Django 5.2.17 on 2026-09-16 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contactpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('source_interaction_id', models.UUIDField(default=None, null=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_notes', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_notes', to='crm.party')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ContextNoteRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('edited_at', models.DateTimeField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_note_revisions', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edited_note_revisions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='crm.contextnote')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contextnote',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='note_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='contextnote',
            constraint=models.CheckConstraint(condition=models.Q(('source_interaction_id__isnull', True)), name='note_no_interaction_yet'),
        ),
        migrations.AddConstraint(
            model_name='contextnote',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='note_workspace_id'),
        ),
        migrations.AddConstraint(
            model_name='contextnoterevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='note_revision_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='contextnoterevision',
            constraint=models.UniqueConstraint(fields=('note', 'version'), name='note_revision_once'),
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_contextnote ADD CONSTRAINT note_person_workspace_fk "
            "FOREIGN KEY (workspace_id, person_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_contextnote DROP CONSTRAINT note_person_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_contextnote ADD CONSTRAINT note_person_subtype_fk "
            "FOREIGN KEY (person_id) REFERENCES crm_person(party_id)",
            "ALTER TABLE crm_contextnote DROP CONSTRAINT note_person_subtype_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_contextnoterevision ADD CONSTRAINT revision_note_workspace_fk "
            "FOREIGN KEY (workspace_id, note_id) REFERENCES crm_contextnote(workspace_id, id)",
            "ALTER TABLE crm_contextnoterevision DROP CONSTRAINT revision_note_workspace_fk",
        ),
    ]
