# Generated by Django 5.2.17 on 2026-09-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contextnote_contextnoterevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='household', serialize=False, to='crm.party')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='organization', serialize=False, to='crm.party')),
            ],
        ),
    ]
