# Generated by Django 5.2.17 on 2026-09-16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crm", "0004_party_subtypes")]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(default=None, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("kind", models.CharField(max_length=80)),
                ("role", models.TextField(default=None, null=True)),
                ("starts_on", models.DateField(default=None, null=True)),
                ("ends_on", models.DateField(default=None, null=True)),
                (
                    "from_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_from",
                        to="crm.party",
                    ),
                ),
                (
                    "to_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_to",
                        to="crm.party",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="relationship_positive_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_party", models.F("to_party")), _negated=True
                        ),
                        name="relationship_distinct_endpoints",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_on__isnull", True),
                            ("ends_on__isnull", True),
                            ("ends_on__gte", models.F("starts_on")),
                            _connector="OR",
                        ),
                        name="relationship_valid_dates",
                    ),
                    models.UniqueConstraint(
                        fields=("workspace", "id"), name="relationship_workspace_id"
                    ),
                ]
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_relationship ADD CONSTRAINT relationship_from_workspace_fk FOREIGN KEY (workspace_id, from_party_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_relationship DROP CONSTRAINT relationship_from_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_relationship ADD CONSTRAINT relationship_to_workspace_fk FOREIGN KEY (workspace_id, to_party_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_relationship DROP CONSTRAINT relationship_to_workspace_fk",
        ),
    ]
