# Generated by Django 5.2.17 on 2026-09-16 12:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField()),
                ('body', models.TextField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_links', to='crm.interaction')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_links', to='crm.party')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField()),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_interaction_revisions', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edited_interaction_revisions', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='crm.interaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionRevisionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_revision_links', to='crm.party')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_links', to='crm.interactionrevision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='interaction_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='interaction_workspace_id'),
        ),
        migrations.AddConstraint(
            model_name='interactionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='interaction_participant_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='interactionparticipant',
            constraint=models.UniqueConstraint(fields=('interaction', 'party'), name='interaction_participant_once'),
        ),
        migrations.AddConstraint(
            model_name='interactionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='interaction_revision_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='interactionrevision',
            constraint=models.UniqueConstraint(fields=('interaction', 'version'), name='interaction_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='interactionrevision',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='interaction_revision_workspace_id'),
        ),
        migrations.AddConstraint(
            model_name='interactionrevisionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='interaction_revision_part_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='interactionrevisionparticipant',
            constraint=models.UniqueConstraint(fields=('revision', 'party'), name='interaction_revision_participant_once'),
        ),
        migrations.AlterModelOptions(
            name='interactionparticipant',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='interactionparticipant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_interactionparticipant ADD CONSTRAINT interaction_participant_parent_workspace_fk FOREIGN KEY (workspace_id, interaction_id) REFERENCES crm_interaction(workspace_id, id)",
            "ALTER TABLE crm_interactionparticipant DROP CONSTRAINT interaction_participant_parent_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_interactionparticipant ADD CONSTRAINT interaction_participant_party_workspace_fk FOREIGN KEY (workspace_id, party_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_interactionparticipant DROP CONSTRAINT interaction_participant_party_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_interactionrevision ADD CONSTRAINT interaction_revision_parent_workspace_fk FOREIGN KEY (workspace_id, interaction_id) REFERENCES crm_interaction(workspace_id, id)",
            "ALTER TABLE crm_interactionrevision DROP CONSTRAINT interaction_revision_parent_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_interactionrevisionparticipant ADD CONSTRAINT interaction_revision_part_parent_workspace_fk FOREIGN KEY (workspace_id, revision_id) REFERENCES crm_interactionrevision(workspace_id, id)",
            "ALTER TABLE crm_interactionrevisionparticipant DROP CONSTRAINT interaction_revision_part_parent_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_interactionrevisionparticipant ADD CONSTRAINT interaction_revision_part_party_workspace_fk FOREIGN KEY (workspace_id, party_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_interactionrevisionparticipant DROP CONSTRAINT interaction_revision_part_party_workspace_fk",
        ),
    ]
