# Generated by Django 5.2.17 on 2026-09-16 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_interaction_interactionparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('due_on', models.DateField(default=None, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('completed', 'completed')], default='open', max_length=10)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to=settings.AUTH_USER_MODEL)),
                ('owed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments_owed', to='crm.party')),
                ('owed_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments_received', to='crm.party')),
                ('source_interaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='crm.interaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_links', to='crm.commitment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitment_links', to='crm.party')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='commitment_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'open')), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='commitment_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='commitment_workspace_id'),
        ),
        migrations.AddConstraint(
            model_name='commitmentperson',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='commitment_person_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='commitmentperson',
            constraint=models.UniqueConstraint(fields=('commitment', 'person'), name='commitment_person_once'),
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitment ADD CONSTRAINT commitment_owed_by_workspace_fk FOREIGN KEY (workspace_id, owed_by_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_commitment DROP CONSTRAINT commitment_owed_by_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitment ADD CONSTRAINT commitment_owed_to_workspace_fk FOREIGN KEY (workspace_id, owed_to_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_commitment DROP CONSTRAINT commitment_owed_to_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitment ADD CONSTRAINT commitment_source_workspace_fk FOREIGN KEY (workspace_id, source_interaction_id) REFERENCES crm_interaction(workspace_id, id)",
            "ALTER TABLE crm_commitment DROP CONSTRAINT commitment_source_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitmentperson ADD CONSTRAINT commitment_person_parent_workspace_fk FOREIGN KEY (workspace_id, commitment_id) REFERENCES crm_commitment(workspace_id, id)",
            "ALTER TABLE crm_commitmentperson DROP CONSTRAINT commitment_person_parent_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitmentperson ADD CONSTRAINT commitment_person_party_workspace_fk FOREIGN KEY (workspace_id, person_id) REFERENCES crm_party(workspace_id, id)",
            "ALTER TABLE crm_commitmentperson DROP CONSTRAINT commitment_person_party_workspace_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_commitmentperson ADD CONSTRAINT commitment_person_subtype_fk FOREIGN KEY (person_id) REFERENCES crm_person(party_id)",
            "ALTER TABLE crm_commitmentperson DROP CONSTRAINT commitment_person_subtype_fk",
        ),
    ]
